name: .NET

on: [pull_request, push ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.1
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.6

    
    - name: Cache NuGet Packages
      id: nugetCache
      uses: actions/cache@v3
      with:
        path: |
          ~/.nuget/packages
          !~/.nuget/packages/unwanted
        key: ${{ runner.os }}-nuget-${{ hashFiles('~/.nuget/packages/*') }}
      
    - name: Restore NuGet Packages
      if: steps.nugetCache.outputs.cache-hit != 'true'
      run: nuget restore MinecraftUSkinEditor.sln
      
    - name: Build Solution
      run: msbuild MinecraftUSkinEditor.sln
